### ISSUE TITLE
Release latest version

### ISSUE THREAD

**Issue by rneal-ck** [milon/barcode#142]
Hi all,

Would it be possible to get a new release tag with the latest fixes? A project I work on is affected by a bug in 8.0.1 that's since been fixed, and we'd prefer to not rely on dev-master in our composer file.

Thanks!

**Comment by downace** [comment]
Also it would be nice if some fixes will be backported to older major versions (6 and 7), because upgrading to the latest version is not always possible due to the dependency on different versions of `illuminate/support`.

As an example, there is a bug in `DNS1D::getBarcodeSVG`: you'll get `Undefined variable: svg` error if you pass `$inline = true`. It's present in 6, 7 and 8 versions and was fixed in e537f93586947c060d2a4b0b99f3726f4ec59d2c (not released on Packagist yet).

**Comment by xorock** [comment]
I fully agree. I have also just been affected by the $inline = true bug and upon analysis I discovered that the 8.0.1 version files were released a year ago.

**Comment by PaolaRuby** [comment]
Released
