### ISSUE TITLE
Getting "invalid image dimensions" error

### ISSUE THREAD

**Issue by felipe-machado** [milon/barcode#39]
Hi, I'm getting this error:

```
ErrorException in DNS2D.php line 195:
imagecreate(): Invalid image dimensions
in DNS2D.php line 195
at HandleExceptions->handleError(2, 'imagecreate(): Invalid image dimensions', '/home/www/api/vendor/milon/barcode/src/Milon/Barcode/DNS2D.php', 195, array('code' => '855544872321115624231', 'type' => 'EAN13', 'w' => 3, 'h' => 3, 'color' => array(0, 0, 0), 'width' => 0, 'height' => 0, 'imagick' => false))
```

when running this code:

`DNS2D::getBarcodePNG('855544872321115624231', 'EAN13');`

Am I missing something? do I have to specify image dimensions somewhere?

Thank you for your help!

**Comment by alesf** [comment]
I too have this problem but on DNS1D class on the same method using the same method with EAN13.

DNS1D::getBarcodePNG('8451703311075', 'EAN13');

Digging into code the problem is with EAN13. See here:
https://github.com/milon/barcode/blob/master/src/Milon/Barcode/DNS1D.php#L1428

It's calculating check digit and it returns false.
@milon **I think it should throw an exception instead.**

Regarding the problem it seems that EAN13 expects no more than 12 digits.

**Comment by krajcikondra** [comment]
Try set storage path:

```
$d = new DNS1D();

// SET STORAGE PATH
$d->setStorPath(__DIR__."/cache/"); 


echo $d->getBarcodeHTML("9780691147727", "EAN13");
```

**Comment by krajcikondra** [comment]
I was send PR

https://github.com/milon/barcode/pull/43

**Comment by Nemes1sX** [comment]
Same issue even I passed my own values.
