### ISSUE TITLE
syntax error, unexpected '.'

### ISSUE THREAD

**Issue by sidjoshi001** [milon/barcode#46]
FatalErrorException in DNS1D.php line 2444:
syntax error, unexpected '.'

Laravel 5.2
Ubuntu 14
PHP 5.5.9
Apache2

**Comment by fbachir** [comment]
hello @milon , i have the some problem of @sidjoshi001 .

**Comment by milon** [comment]
Could you send me the whole codeblocks and error message?

**Comment by sidjoshi001** [comment]
@fbachir It's Version Issue... Downgrade to 5.2.1

https://packagist.org/packages/milon/barcode#5.2.1

**Comment by henriksjodahl** [comment]
@milon I'ts been this way since V5.3.4 because of these lines:
https://github.com/milon/barcode/blob/master/src/Milon/Barcode/DNS1D.php#L2444
https://github.com/milon/barcode/blob/master/src/Milon/Barcode/DNS1D.php#L2456

There are three dots in the method call. I don't have the time to do a PR, hopefully someone else may fix them.

**Comment by milon** [comment]
Hey, if you use php 5.6, it will fix automatically. I am outside of my home town now. Will fix it this weekend.

**Comment by mikealmond** [comment]
The `composer.json` should have been updated to reflect the php version requirements. Right now it's says 5.4, when it should be 5.6

**Comment by alexrindone** [comment]
This is not working for me even after downgrade to 5.2
I am using laravel 5.2

**Comment by eajahuanca** [comment]
FatalErrorException in DNS2D.php line 423: 
syntax error, unexpected '.'
Laravel 5.2
Windows 8
PHP 5.5.11
help me please!!!

**Comment by henriksjodahl** [comment]
@eajahuanca you need at least PHP 5.6. 5.5 are not supported
